# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학, 수학 연산에 자주 사용
- Numpy의 강력한 기능 : 배열 -> 행렬(선형대수)
- 선형대수, 푸리에 변환 -> 수학 함수들을 제공
- 속도가 빠름

In [3]:
# numpy 모듈을 np라는 별명으로 사용하겠다 !
import numpy as np

## 1차원 배열

In [178]:
# 1차원 배열 생성
a = np.array([1, 2, 3, 4])

In [172]:
print(a)

[1 2 3 4]


In [173]:
# list와 다른 점
l = [1, 2, 3, 4]
print(l)
# list는 콤마로 나누어져 있음

[1, 2, 3, 4]


In [174]:
# 배열 축의 크기
print(a.shape)
# 4행, 0열 - 튜플 형태로 뜸

(4,)


In [175]:
# 배열의 차원
print(a.ndim)

1


In [176]:
# 배열의 데이터 타입
print(a.dtype)

int64


In [177]:
# 각 요소의 바이트 단위 크기
print(a.itemsize)

8


## 2차원 배열

In [18]:
b = np.array([[1, 2], [3, 4]])  # 대괄호가 2개 쓰임
print(b)

[[1 2]
 [3 4]]


In [29]:
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

2
int64
8
32


## 3차원 배열

In [67]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 대괄호가 3개 쓰임
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [68]:
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

3
int64
8
64


## 스칼라
: 하나의 숫자값

In [34]:
s = np.array(1)
print(s)

1


## 용어 정리

* **1차원 : 벡터(Vector)**
```
v = np.array([1, 2, 3])
print(v)
```
* **2차원 : 행렬(Matrix)**
```
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m)
```
* **3차원 : 텐서(Tensor)**
```
t = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(t)
```



## for문으로 배열 생성

In [35]:
f = np.array([i for i in range(0, 10, 2)])  # (start, end, step)

In [36]:
print(f)

[0 2 4 6 8]


In [38]:
# 데이터의 속성 파악을 습관들이기
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

1
int64
8
40


## 데이터 타입 (numpy에서 다루는)

* 1. 숫자형
* 2. 문자형
* 3. 논리형


### 1.숫자형

**- 부호가 있는 정수 (Signed integer)**

  : int (8bit, 16bit, 32bit, 64bit) -> 저장할 수 있는 값의 범위

  --> 8bit는 8bit까지만 저장 가능, 16은 16까지 저장 가능

  --> 데이터의 크기를 효율적으로 관리하기 위해서

**- 부호가 없는 정수 (Unsigned integer)**

**- 실수 (floating point)**

**- 복소수 (complex)**

In [51]:
# int - 부호가 있는 정수

# 리스트 형태로 값을 넣을 수 있음
data = [1.1, 2, 3]

# 데이터 타입 지정도 가능
i = np.array(data, dtype = np.int32)
print(i)
print(i.dtype)

[1 2 3]
int32


In [47]:
# uint - 부호가 없는 정수
data2 = [-1, 2, 3]

ui = np.array(data2, dtype = np.uint32)
print(ui)

# uint는 각 8, 16, 32, 64마다 처리 가능한 범위가 있고
# 내가 지정한 32의 범위는 0 ~ 4,294,967,295 이다.
# -1은 저 범위에서 포함되지 않기 때문에 거꾸로 돌아서 제일 큰 값이 출력됨

[4294967295          2          3]


In [50]:
# float - 실수
f = np.array(data, dtype = np.float64)
print(f)
# 2.0 / 3.0으로 출력

[1.1 2.  3. ]


In [53]:
# complex - 복소수
c = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype = np.complex64)

In [54]:
print(c.real)  # 실수
print(c.imag)  # 허수

[1. 3. 5.]
[2. 4. 6.]


### 2.문자형 데이터

- string_
- unicode_
- string은 unicode보다 데이터크기가 더 작음
- 문자형으로 저장은 해야하지만 사용자가 읽을 일은 없을 때는 데이터 크기가 작은 string으로 저장
- 사용자가 시각적으로 보기 편리하되 데이터가 크기가 큰 건 unicode

#### string_

In [55]:
data = [1, 2, 3]

In [56]:
s = np.string_(data)
print(s)

# b = byte 를 의미

b'\x01\x02\x03'


In [57]:
print(s.dtype)
# S3 = string 3개

|S3


In [58]:
data3 = [1, 2, 3, 4, 5]

s2 = np.string_(data3)   # s2_ = np.array(data3, dtype='S) 로도 사용 가능
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


#### unicode_

In [59]:
u = np.array(data3, dtype='U')  # 'U' = unicode

print(u)
print(u.dtype)
# dtype의 U1은 자릿수를 의미

['1' '2' '3' '4' '5']
<U1


In [61]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype='U')
print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


### 3.논리형 (boolean)

- True(1), False(0)

[ 비트 연산 사용 ]

& and

| or

^ xor

~ not

In [62]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [65]:
# and 연산자
and_ = np.logical_and(l1, l2)
print(and_)

[False False False]


In [66]:
# or 연산자
or_ = np.logical_or(l1, l2)
print(or_)

[ True  True  True]


## 데이터 형 변환 (Cast, Casting)

- 데이터들끼리 형태를 맞춰주는 목적
- 맞춰주는 이유는? 각 데이터마다 갖고 있는 체계가 다름
- 형 변환 -> 각 데이터가 어떤 데이터인지 알고, 변환의 목적성이 있어야함

ex) 이미지 데이터 -> uint형으로 불러옴 -> 분석 시 float로 변환

ex) RGB값은 0~255까지 있음. 음수는 필요 없어서 int를 uint로 바꾸기도 함

In [1]:
data = [1.1, 2, 3]

In [6]:
# int -> float
a = np.float64(data)  # np.데이터타입
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [71]:
# 위에서 바꾼 float -> int
a = a.astype(np.int64)
print(a)
print(a.dtype)

[1 2 3]
int64


In [2]:
# float -> int 또 다른 방법
a = np.int64(data)
print(a)
print(a.dtype)

[1 2 3]
int64


In [76]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [77]:
b = b - 1
print(b)
print(b.dtype)

# uint16에 0값을 넣고 값을 넣은 b 변수에 -1을 했을 때
# 위에서 봤던 것처럼 범위의 마지막값이 나오는 것이 아니라
# 컴퓨터가 알아서 데이터를 변환시켜줘서 int형으로 나오고 -1값이 나옴

-1
int64


In [79]:
# b와 다르게 -1을 uint에 직접 넣으면 16의 마지막값이 나옴
c = np.uint16(-1)
print(c)

65535


## 산술연산

In [80]:
# time 모듈로 진짜 빠른지 확인해보기
import time

In [89]:
data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

In [90]:
print(len(data))
print(len(data2))

2
2


In [91]:
print(len(data[0]))

3


* for문을 사용한 연산



In [92]:
sum = 0

for i in range(len(data)) :
  for j in range(len(data[0])) :  # data의 각 리스트에 값이 3개이기 때문(단순한 인덱스값) -> range(3)이라고 써도 됨
    print('i: ',i, 'j: ', j)

i:  0 j:  0
i:  0 j:  1
i:  0 j:  2
i:  1 j:  0
i:  1 j:  1
i:  1 j:  2


In [93]:
# data에 접근하기 위해서는 data[i][j] -> data가 2차원배열(행렬Matrix)이기 때문
sum = 0

for i in range(len(data)) :
  for j in range(len(data[0])) :
    sum += data[i][j]

print(sum)

21


* numpy를 사용한 연산

In [95]:
# 사칙연산 가능
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum = a + b
min = a - b
mul = a * b
div = a / b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### 지수와 로그 계산

In [96]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

aa = np.exp(a)  # exp = 지수함수
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [97]:
bb = np.log(b) # log = 자연로그
print(bb)

[1.38629436 1.60943791 1.79175947]


In [98]:
cc = np.log2(b) # 밑이 2인 로그
print(cc)

[2.         2.32192809 2.5849625 ]


### 삼각함수

In [99]:
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)

cos_ = np.cos(d)

tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 배열의 연결과 분할

- 0 : 세로방향
- 1 : 가로방향

## 배열의 연결

In [100]:
print('a' + 'b')

ab


* 정방 행렬 : 정사각형처럼 생김 (ex. 2x2, 3x3, 4x4)

* 연결 전제조건 : 배열의 차원수가 같아야함

  -- a x b 와 b x a 처럼 앞뒤가 같아야함

* 2x3
```
[[1, 2, 3],
[4, 5, 6]]
```
* 3x2
```
[[1, 2],
[3, 4],
[5, 6]]
```
이렇게 같은 경우,

  [1, 4]와 [1, 2]

  [2, 5]와 [3, 4]

  [3, 6]와 [5, 6] 

  이렇게 계산됨


In [31]:
x = [1, 2, 3]
y = [4, 5, 6]

In [32]:
concat = np.concatenate([x, y])
print(concat)

[1 2 3 4 5 6]


In [33]:
x2 = [[1, 2], [3, 4]]  # 2x2
y2 = [[5, 6], [7, 8]]  # 2x2

In [34]:
concat2 = np.concatenate([x2, y2])
print(concat2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
# axis = 1 추가
concat2 = np.concatenate([x2, y2], axis = 1)  # 열
print(concat2)
# 열이 늘어남

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
concat2 = np.concatenate([x2, y2], axis = 0)  # 행
print(concat2)
# 행이 늘어남

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [112]:
# 또 다른 배열 만드는 법 - arange
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [113]:
# 위에서 만든 배열을 reshape 할 수 있음
arr.reshape(2, 5)  # 위의 숫자 10에 맞게 지정

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [114]:
x2 = [[1, 2], [3, 4]]
y2 = [[5, 6], [7, 8]]

# hstack horizontal - 수평 -> 열 증가
h = np.hstack([x2, y2])
print(h)

# vstack vertical - 수직 -> 행 증가
v = np.vstack([x2, y2])
print(v)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 배열의 분할

* hsplit
* vsplit

In [116]:
# hsplit

x2 = np.array([[1, 2], [3, 4], [5, 6]])

h2 = np.hsplit(x2, 2)
print(h2)

# 열 방향으로 잘라서 array 2개를 출력

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [118]:
# 행렬을 그림에 대입시켜서 생각해보기
print(x2.shape)

(3, 2)


In [119]:
x2 = np.array([[1, 2], [3, 4], [5, 6]])

v2 = np.vsplit(x2, 3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


## 다양한 배열 만들기

* 항등식 만들 때, 0 행렬과 1 행렬 사용

In [121]:
# 0 행렬
zero = np.zeros([3, 4])
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [122]:
# 1 행렬
one = np.ones([3, 4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [124]:
# 대각행렬 (정방형으로만 가능)
# 행렬할 때 곱하기하면 자기 자신이 나오게 함
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy 제공 함수

## 범용 함수

In [125]:
# 절댓값 함수 = np.abs
# array를 음수로 만든 뒤, 절댓값으로 변환
arr1 = np.array([-1, -2, -3, -4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [127]:
# 제곱근
arr2 = np.array([1, 9, 4, 16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 3. 2. 4.]


## 집계 함수

In [130]:
# 평균값 - mean
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a)

print(a_mean)

3.0


In [132]:
# 중앙값 - median
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b)

print(b_median)

5.0


In [134]:
# 표준편차 - std
c = np.array([1, 2, 3, 4, 5])
std_arr = np.std(c)

print(std_arr)

1.4142135623730951


In [135]:
# 분산값 - var
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d)

print(d_var)

2.0


In [137]:
# 합계 - sum
d = np.array([1, 2, 3, 4, 5])
d_sum = np.sum(d)

print(d_sum)

15


In [138]:
# 누적 합계 - cumsum
d_cumsum = np.cumsum(d)
print(d_cumsum)
# cumsum은 배열로 반환 (sum은 숫자를 반환)

[ 1  3  6 10 15]


In [143]:
# 최솟값 - min
d = np.array([1, 2, 3, 4, 5])
min_arr = np.argmin(d)

print(min_arr)  # index값을 반환
print(d[min_arr]) # d[0]

0
1


In [144]:
# 최댓값 - max
d = np.array([1, 2, 3, 4, 5])
max_arr = np.argmax(d)

print(max_arr)  # index값을 반환
print(d[max_arr])  # d[4]

4
5


In [146]:
# any - 배열 안에 True가 하나라도 있으면 True 반환
a = np.array([0, 0, 0, 1])
b = np.array([0, 0, 0, 0])

a_true = np.any(a)
print(a_true)

b_true = np.any(b)
print(b_true)

True
False


In [147]:
# all - 모든 값이 1이거나 True일 때만 True 반환
a_all = np.all(a)
print(a_all)

False


In [149]:
# NaN
a = np.array([1, 2, np.nan, 4])
print(a)

# nan값을 0으로 대체하여 합계
a_nsum = np.nansum(a)
print(a_nsum)

[ 1.  2. nan  4.]
7.0


In [151]:
# nan값이 있는 배열을 그냥 sum으로 연산했을 때
a = np.array([1, 2, np.nan, 4])
a_sum = np.sum(a) 
print(a_sum)
# nan값이 반환됨

nan


In [154]:
# 조건에 맞는 값 찾기 - where
d = np.array([1, 2, 3, 4, 5])

condition = np.where(d < 3)
print(condition)
# tuple 형태로 index 값을 변환(마지막이 콤마로 끝남)

(array([0, 1]),)


In [157]:
# 조건에 맞지 않지 않는 값 채우기
d = np.array([1, 2, 3, 4, 5])

condition = np.where(d < 3, d, 0)   # 조건에 맞지 않는 값은 0으로 채우기
print(condition)

# 채우는 값에 따라 반환되는 형태가 달라짐
# 채우는 값을 문자열로 넣으면 모든 값이 문자열로 반환

[1 2 0 0 0]


## Boolean Indexing
조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [160]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # 원본데이터는 건들지 않는다 !

even_a = a[a % 2 == 0]  # 조건에 맞는 애들만 even_a에 담기
print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


## Broadcast (브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해준다.
- ex) 1차원 - 2차원 간의 연산을 가능하게 함

[조건]
1. 두 배열의 차원수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때까지 1을 추가한다.
2. 두 배열의 차원수가 같을 경우, 크기가 1인 차원이 있으면 그 배열은 다른 배열의 크기에 일치하도록 복제된다.
3. 두 배열의 차원수가 같을 경우, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.


In [161]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [163]:
# 크기와 차원이 같으면 사칙연산 가능
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [165]:
d = np.array([[1], [2], [3]])  # 2차원 배열(행렬) 3x1
e = np.array([4, 5, 6])   # 1차원 배열(벡터)

f = d + e
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


* 어떻게 다른 차원이 맞춰지는걸까?
* e값을 1x3로 바꾸려면 어떻게 해야할까?

In [166]:
# e의 각 값을 []로 감싸면?
d = np.array([[1], [2], [3]])
e = np.array([[4], [5], [6]]) 

f = d + e
print(f)

# e는
# 3x1 배열이 만들어짐

[[5]
 [7]
 [9]]


In [170]:
# 값을 통째로 []에 담으면? -> 1차원에서 2차원으로
d = np.array([[1], [2], [3]])
e = np.array([[4, 5, 6]])

f = d + e
print(f)

# e가 1x3으로 잘 바뀜
# 그래서 결과가 3x3으로 잘 나옴 !

[[5 6 7]
 [6 7 8]
 [7 8 9]]


---

# 복습 문제

4.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수

# 내 풀이
concat = np.concatenate([arr1, arr2, arr3])
print(concat)

[ 1  2  3  4  5  6  7  8  9 10]


4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.

In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# mean() 함수 응용하기

# 내 풀이
mean_ = np.array([])
for i in range(len(arr)) :
  a = np.mean(arr[i])
  b = np.array([a])
  print(np.concatenate([b]))

# 강사님 풀이
np.mean(arr, axis=0) 

[2.]
[5.]
[8.]


array([4., 5., 6.])

4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.

In [38]:
# np.max()

# 내 풀이
print(np.max(arr, axis = 1))

[3 6 9]


4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.

In [39]:
# linspace()

# 강사님 풀이
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.

- 
def sum_of_evens(arr: np.ndarray) -> int:


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 내 풀이
def sum_of_evens(arr) :
  return np.sum(arr[arr % 2 == 0])
print(sum_of_evens(arr))

# 강사님 풀이
def sum_of_evens(arr: np.ndarray) -> int :
  return np.sum(arr[arr % 2 == 0])
print(sum_of_evens(arr))

30
30


4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

In [56]:
# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)

원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 1. 수평분할하기 -> 다시 원본으로 스택쌓기
# 2. 수직분할하기 -> 다시 원본으로 스택쌓기

In [58]:
# 내 풀이

# 1. 수평분할하기 -> 다시 원본으로 스택쌓기
# 수평 -> 가로 -> 1, vsplit, vstack
# 분할
arr1 = np.vsplit(arr, 3)
print('수평 분할 :')
print(arr1)
# 다시 원본으로 연결
arr11 = np.vstack(arr1)
print('다시 원본으로 :')
print(arr11)

print('--------------------------------')
# 2. 수직분할하기 -> 다시 원본으로 스택쌓기
# 수직 -> 세로 -> 0, hsplit, hstack
arr0 = np.hsplit(arr, 4)
print('수직 분할 :')
print(arr0)
arr00 = np.hstack(arr0)
print('다시 원본으로 :')
print(arr00)

수평 분할 :
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
다시 원본으로 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------
수직 분할 :
[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]
다시 원본으로 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.

In [59]:
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
print(arr)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]


In [75]:
# 내 풀이
arr_ = np.where(arr % 10 == 0, arr, 0)
print(arr_)

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오

In [76]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

In [77]:
# 내 풀이
n = a[a % 2 == 0]
print(n)

[2 4 6 8]


4.9 각도를 이용해서 삼각함수를 만들어봅시다.

In [78]:
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

angle

1.0471975511965976

In [79]:
# 강사님 풀이
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

사인 값: 0.8660254037844386
코사인 값: 0.5000000000000001
탄젠트 값: 1.7320508075688767


4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.

In [88]:
arr = np.array([1, 2, 3, 4, 5])

In [90]:
# 내 풀이
new_arr = np.where(arr % 2 == 1, arr, arr*2)
print(new_arr)

[1 4 3 8 5]


In [91]:
# 강사님 풀이
new_arr = np.where(arr % 2 == 0, arr * 2, arr)
print("조건을 만족하는 요소를 2배로:", new_arr)

조건을 만족하는 요소를 2배로: [1 4 3 8 5]
