문제를 풀어봅시다.
1일차 - 쉬운 문제부터 스타트

# 배열

### 사이즈 10의 Null(0) 1차원 배열을 만들어보세요.

In [ ]:
import numpy as np



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 내 풀이
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

차원 만드는 넘파이 함수를 사용해보겠습니다.
### 값이 10 ~ 49 인 1차원 배열을 만들어주세요.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# 내 풀이
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 0~8 까지의 값을 사용하여 `3x3` 배열을 만드시오

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# 내 풀이
c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 강사님 풀이
Z = np.arange(9).reshape(3, 3)
Z

### (응용) 5x5 배열을 만들어서 경계값만 1이고, 내부에 있는 값은 0 인 2차원 배열을 만들어 보세요


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# 내 풀이
a = np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]])
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# 강사님 풀이
Z = np.ones((5,5))
Z[1:-1, 1:-1] = 0
Z

# 랜덤

오늘 배운 랜덤함수를 사용해서 문제를 풀어보겠습니다.

### 랜덤 값이 있는 `3x3x3` array 만들기

array([[[0.74453246, 0.9040558 , 0.66151847],
        [0.43331527, 0.97965292, 0.97638912],
        [0.66104214, 0.62926961, 0.25918641]],

       [[0.57411902, 0.06307186, 0.52951538],
        [0.33133679, 0.76366474, 0.20418361],
        [0.09254982, 0.51898777, 0.78546247]],

       [[0.28486858, 0.86309618, 0.98166195],
        [0.17052157, 0.59134514, 0.1685133 ],
        [0.14101175, 0.47464965, 0.93869371]]])

In [19]:
# 내 풀이
a = np.random.rand(3, 3, 3)
a

array([[[0.38515648, 0.10736621, 0.49226489],
        [0.70086027, 0.44816754, 0.90236796],
        [0.37089064, 0.51483726, 0.94397089]],

       [[0.60523648, 0.61437866, 0.25701314],
        [0.46055747, 0.85422034, 0.79998794],
        [0.24029079, 0.58409974, 0.73521676]],

       [[0.34950605, 0.02745314, 0.2546074 ],
        [0.52976731, 0.42631503, 0.42326679],
        [0.60256428, 0.25320993, 0.32503532]]])

### 랜덤 값이 있는 `10x10` 배열을 만들고 최소값과 최대값을 찾아주세요

0.004985215945142785 0.9950260426491608


In [21]:
# 내 풀이
a = np.random.rand(10, 10)
print(a.min(), a.max())

0.04632358459085828 0.9926469974388071


### 30 크기의 랜덤 값을 가지는 1차원 배열을 만들어서 평균값을 도출해주세요.

[0.41527747 0.23871271 0.15981916 0.06378559 0.0219653  0.09542384
 0.86913623 0.7900542  0.29314164 0.33290257 0.32919346 0.0973356
 0.89723669 0.88440698 0.95469159 0.1740947  0.58400673 0.33043558
 0.32677392 0.54671053 0.7400089  0.07739969 0.42578189 0.13814556
 0.51986336 0.61243761 0.79491561 0.23894515 0.18308399 0.84377674]
0.43264876538884134


In [25]:
# 내 풀이
a = np.random.rand(30)
print(a)
print(a.mean())

[0.70365916 0.13022891 0.96452259 0.27021525 0.42236301 0.14953736
 0.71623025 0.62247586 0.01847539 0.96034666 0.31766392 0.47916399
 0.1754034  0.43154154 0.42808566 0.11412833 0.18566349 0.50108963
 0.47801192 0.10937755 0.12804661 0.50777767 0.99217858 0.15300921
 0.97171622 0.79932669 0.17883336 0.81298889 0.73026964 0.80119033]
0.47511736985815023


# 행렬

행렬 연산을 해보겠습니다.
### 1로 채워진 `5x3` 행렬과 `3x2` 행렬의 곱을 구해봅니다.


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [79]:
# 내 풀이
a = np.ones([5, 3])
b = np.ones([3, 2])
a @ b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# 강사님 풀이
X, Y = np.ones((5,3)), np.ones((3,2))
Z = np.dot(X, Y)
print(Z)

# @ = dot
z = X @ Y
z

### (응용) 행렬의 연산을 하고 제로행렬 C 에 에 값을 덮어씌워주세요.
- np.add() 함수의 매개변수를 응용합니다. 

In [28]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [35]:
# 내 풀이
x = A * B
x

array([ 4, 10, 18])

In [31]:
C = np.zeros(3)
C

array([0., 0., 0.])

In [38]:
c = np.add(x, C)
c

array([ 4., 10., 18.])

In [ ]:
# 강사님 풀이
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)

np.add(A, B, out=C)
C

### (응용) A 배열의 모든 요소의 부호를 반전시켜서 C에 값을 덮어씌워주세요.
- np.negative()

array([-1., -2., -3.])

In [39]:
# 내 풀이
a = np.negative(A)
a

array([-1, -2, -3])

In [40]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [41]:
c = np.add(a, b)
c

array([-1., -2., -3.])

In [ ]:
# 강사님 풀이
np.negative(A, out= C)
C

### 크기 10개의 1차원 랜덤 행렬을 만들고 최대값을 0 으로 바꾸어 주세요
1. 최대값이 어디에 있는 지 인덱스를 확인하면
2. 인덱싱을 통해서 최대값을 0으로 바꿔줄 수 있습니다.
3. argmax() 함수는 배열의 요소들 중에서 가장 큰 값이 있는 위치의 인덱스를 반환합니다.

최대값이 있는 인덱스: 6


array([0.66014341, 0.01146348, 0.42875575, 0.18203216, 0.6988441 ,
       0.12685795, 0.        , 0.83880586, 0.07273523, 0.68039686])

In [42]:
# 내 풀이
a = np.random.rand(10)
a

array([0.0236905 , 0.46399016, 0.06121075, 0.0335247 , 0.16917682,
       0.24944268, 0.86357774, 0.78144716, 0.98237422, 0.20396747])

In [45]:
print('최대값이 있는 인덱스: ',a.argmax())
a[8] = 0
a

최대값이 있는 인덱스:  6


array([0.0236905 , 0.46399016, 0.06121075, 0.0335247 , 0.16917682,
       0.24944268, 0.86357774, 0.78144716, 0.        , 0.20396747])

In [ ]:
# 강사님 풀이
Z = np.random.random(10)
print('최대값이 있는 인덱스:',Z.argmax())
Z[Z.argmax()] = 0
Z

### np.max 와 np.argmax 의 값을 확인해봅시다.

- 각 열과 행별로 최댓값을 반환하고 인덱스를 호출해주세요



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr에서 최댓값: 6
arr에서 최댓값인 6이 위치한 인덱스: 5
arr에서 각 열(axis=0)별로 최댓값을 반환: [4 5 6]
arr에서 각 열(axis=1)별로 최댓값을 반환: [3 6]
arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환: [1 1 1]
arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환: [2 2]


In [46]:
# 내 풀이
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [51]:
print('arr에서 최댓값: ',arr.max())
print('arr에서 최댓값의 인덱스:', arr.argmax())
print('arr에서 각 열별로 최댓값: ', arr.max(axis=0))
print('arr에서 각 행별로 최댓값: ', arr.max(axis=1))
print('arr에서 각 열별로 최댓값의 인덱스: ', arr.argmax(axis=0))
print('arr에서 각 행별로 최댓값의 인덱스: ', arr.argmax(axis=1))

arr에서 최댓값:  6
arr에서 최댓값의 인덱스: 5
arr에서 각 열별로 최댓값:  [4 5 6]
arr에서 각 행별로 최댓값:  [3 6]
arr에서 각 열별로 최댓값의 인덱스:  [1 1 1]
arr에서 각 행별로 최댓값의 인덱스:  [2 2]


In [ ]:
# 강사님 풀이
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr에서 최댓값:', np.max(arr))
print('arr에서 최댓값인 6이 위치한 인덱스:',np.argmax(arr))
print('arr에서 각 열(axis=0)별로 최댓값을 반환:', np.max(arr, axis=0))
print('arr에서 각 행(axis=1)별로 최댓값을 반환:', np.max(arr, axis=1))
print('arr에서 각 열(axis=0)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=0))
print('arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=1))

# 형변환

### 균일분포의 랜덤함수를 이용해서 0 ~ 100 까지 값을 가지는 1차원 실수 (32비트) 행렬을 만듭니다.

In [1]:
# 내 풀이 - 모르겠음

In [ ]:
# 강사님 풀이
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

### 정수 (32비트) 이면서 배열의 모양을 `10x1` 로 변환해주세요 

In [4]:
# 내 풀이 -> 모르겠음

In [ ]:
# 강사님 풀이
X = Z.view(np.int32)
X.shape = (10,1)
X

## view() 함수와 astype() 함수는 NumPy 배열에서 각각 다른 목적을 가지고 사용되는 함수입니다.

둘의 함수를 사용해서 차이를 이해해보세요 ^^

array([44.841415, 95.26812 , 17.033804, 61.530926,  9.098388, 65.942726,
       73.896355, 23.109636, 37.050285, 72.628746], dtype=float32)

array([[1110662556],
       [1119783239],
       [1099449659],
       [1115037611],
       [1091670783],
       [1115939501],
       [1116981999],
       [1102635145],
       [1108620158],
       [1116815851]], dtype=int32)

In [5]:
# 내 풀이 - 모르겠음

### 집계 함수로 배열에 Null 값이 있는지 확인해보세요.
- 정수형 난수로 `3x10` 행렬을 생성합니다.
- 0 ~ 5 까지의 값으로 만들어주세요.

array([[3, 0, 4, 2, 2, 1, 4, 1, 2, 2],
       [0, 4, 0, 5, 3, 0, 4, 3, 2, 4],
       [4, 3, 0, 3, 2, 0, 0, 3, 1, 0]])

In [58]:
# 내 풀이 : 행렬 먼저 만들기
a = np.random.randint(0, 5, (3, 10))
a

array([[3, 2, 3, 0, 0, 1, 0, 2, 1, 0],
       [0, 0, 3, 1, 4, 2, 2, 1, 3, 1],
       [3, 1, 3, 4, 4, 2, 4, 4, 3, 3]])

True

In [63]:
# 내 풀이 : null값 있는지 확인 -> 모르겠음

TypeError: ignored

In [ ]:
# 강사님 풀이
Z = np.random.randint(0,6,(3,10))
print(Z)
Z.any() # == np.any(Z)

# 정규분포, 균일분포


정규분포 normal()을 따르는 난수 생성의 방법을 배웠습니다.
이번에는 주어진 범위에서 균일분포를 따르는 난수 생성을 해보겠습니다.

- Normal Distribution
- Uniform Distribution





> [low, high] 범위에서 균일 분포를 따르는 난수 생성


> random_number = np.random.uniform(low, high, size)

### (응용) 0부터 1사이의 10개의 값을 가지는 균일분포 배열을 만들어주세요
- 배열에서 지정된 값에서 가장 가까운 값을 찾겠습니다. => 정답 인덱스 호출 => 가장 가까운 값 호출
- num = 0.5 








[0.9622446  0.7966455  0.15172051 0.32459544 0.43147498 0.55822707
 0.3355717  0.87061099 0.83910581 0.29042325]


5

0.5582270718026265

In [65]:
# 내 풀이
a = np.random.uniform(0, 1, (10))
print(a)

# 0.5와 가장 근접한 값을 찾는게 뭔지 모르겠음

[0.49692283 0.50915633 0.30611777 0.64643822 0.35276701 0.62482262
 0.74033534 0.77834882 0.36078218 0.61858693]


In [ ]:
# 강사님 풀이
Z = np.random.uniform(0,1,10)
print(Z)
num = 0.5
np.abs(Z-num).argmin()

Z[np.abs(Z-num).argmin()]

### (응용) 다차원의 배열을 1차원으로 평면화 하는 flatten 함수로 응용해보겠습니다.

- np.flatten()
- 3차원의 배열을 -> 1차원으로 평면화 하고 -> 최대값을 10으로 변경해주세요

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])


5
[[ 1  2  3]
 [ 4  5 10]
 [ 3  4  5]]


In [78]:
# 내 풀이
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])
arr2 = arr.flatten() # 평면화
print(arr2.argmax())

arr2[5] = 10
arr2 = np.reshape(arr2, (3, 3))
print(arr2)

5
[[ 1  2  3]
 [ 4  5 10]
 [ 3  4  5]]


In [ ]:
# 강사님 풀이
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])

# 다차원 배열을 1차원으로 평면화
flattened_arr = arr.flat
print(arr.argmax())

# 최대값을 갖는 인덱스의 값을 10으로 변경
flattened_arr[arr.argmax()] = 10

# 평면화된 1차원 배열의 요소에 접근 가능하므로, 최대값을 갖는 인덱스에 접근하여 값 변경도 가능

print(arr) # 원본 다차원 배열 arr에도 해당 변경이 반영되는 것을 확인할 수 있습니다.

### (응용) 4차원(3,4,3,4)으로 주어진 범위(0,10) 안에서 정수형 변수를 생성해주세요
- 마지막 2축(axis)에서 합계를 출력해보세요

array([[61, 51, 40, 66],
       [33, 52, 43, 52],
       [64, 56, 46, 70]])

In [ ]:
# 내 풀이 - 모르겠음

In [ ]:
# 강사님 풀이
A = np.random.randint(0,10, (3,4,3,4))
A.sum(axis = (-2,-1))

### 배열의 첫번째 행과 두번째행을 바꾸어 봅시다

In [ ]:
A = np.arange(25).reshape(5,5)


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# 내 풀이 - 모르겠음

In [ ]:
# 강사님 풀이
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

# arg 인덱스 접근 함수 추가

- argmax. argmin 을 응용하기

(응용) 표준정규분포를 사용해서 100개의 난수를 생성해주세요.

그 후 shuffle() 함수를 사용해서 순서를 섞어줍니다.

sort() 함수와 마찬가지로 argsort() 를 이용해 인덱스를 사용합니다

- argsort() 를 사용해서 가장 큰 값을 5개만 뽑아봅시다.

None


array([1.43566383, 1.57839459, 1.73572719, 2.03275258, 3.19506051])

In [83]:
# 내 풀이 - 모르겠음
a = np.random.normal(0, 1, 100)
np.random.shuffle(a)
a.argsort()

array([87, 65, 66, 25,  1, 79, 22, 28, 78,  2, 69, 64, 52, 83,  7, 91, 93,
       54, 41, 44, 43,  4, 62, 23, 56, 61, 34, 72, 38, 71, 81, 53, 85, 31,
       42, 73, 26, 82, 76, 11, 92, 95, 18, 90, 84, 29, 70, 16, 47, 97, 94,
       15, 33, 35, 60, 89, 98, 21, 55, 96, 46,  5,  0,  8, 36, 74, 45, 68,
       27, 19, 13, 75, 51, 24, 20, 12, 17, 77, 40, 67, 50, 99, 59, 57,  6,
       30, 37, 88, 48, 39,  3,  9, 86, 49, 32, 10, 58, 63, 14, 80])

In [ ]:
# 강사님 풀이
Z = np.random.randn(100)
np.random.shuffle(Z)

Z[np.argsort(Z)[-5:]]

arr = np.array([1, 3, 2, 5, 4])

# 최댓값의 인덱스
max_index = np.argmax(arr)
print("Max index:", max_index)  

# 최솟값의 인덱스
min_index = np.argmin(arr)
print("Min index:", min_index)  

# 조건을 충족하는 요소의 인덱스
index = np.argwhere(arr > 2)
print("Indices greater than 2:", index)  # 반환값 2차원 [[1] [3] [4]]

# 조건에 따라 요소 선택 및 인덱스 반환
selected_index = np.where(arr > 2)
print("Selected indices:", selected_index)  

# 0이 아닌 요소의 인덱스
nonzero_index = np.nonzero(arr)
print("Nonzero indices:", nonzero_index)  