[ 브로드 캐스팅 ]
- 두 배열의 차원의 크기가 같다 -> 그냥 계산
- 두 배열의 차원이 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때, 계산이 가능한 경우, 차원이 늘어남

(계산이 가능할 때, 차원이 작은 애를 큰 애에게 맞춰준다.)

# 난수 생성 함수

* random 모듈 사용
* 표준편차 구할 때 등등

In [1]:
import numpy as np

## rand

* **0과 1 사이의 값**을 랜덤으로 출력해줌

In [2]:
a = np.random.rand(2, 2)
print(a)

[[0.29248565 0.95186506]
 [0.93261994 0.91360075]]


## randn
* 표준 정규 분포 안에서 랜덤 값을 만들어줌
(표준 정규 분포: 평균이 0, 분산은 1)

In [4]:
b = np.random.randn(2, 2)
print(b)

[[-1.23958142  3.17181855]
 [-0.9765344   1.81664022]]


## randint
* 정수값으로 랜덤 출력


```
np.random.randint(최솟값, 최댓값, size=갯수)
```
-- 최솟값과 최댓값을 포함하여 값이 출력됨


In [5]:
c = np.random.randint(0, 10, size=5)
print(c)

[0 7 8 6 2]


* size = (튜플)로 값을 넣으면 결과값으로 행렬이 출력됨

In [7]:
c2 = np.random.randint(0, 10, size=(2, 2))
print(c2)

[[0 3]
 [5 6]]


## shuffle

* shuffle을 사용한 값을 변수에 넣어 print를 할 수 없음
* 왜냐하면, shuffle을 사용함과 동시에 그 원본값이 변하기 때문에

In [14]:
d = np.arange(5)  # 0 ~ 9까지의 값을 생성
np.random.shuffle(d)  # shuffle : 무작위로 섞음 / 원본값이 변하기 때문에 복사본 생성이 안됨
print(d)

[4 3 1 2 0]


## choice

* 갯수를 정하여 랜덤으로 값을 뽑을 수 있음
```
np.random.choice(데이터, 뽑을 갯수)
# 중복허용 (같은 수가 겹쳐서 나올 수 있음)
```

* 중복을 허용하고 싶지 않을 때
```
np.random.choice(데이터, 뽑을 갯수, replace=False)
```
* 확률을 지정하고 싶을 때
```
np.random.choice(d, 5, p=[0.1, 0, 0.3, 0.4, 0.2])
# p의 값이 1이어야함
```




In [11]:
# 중복 허용
choice = np.random.choice(d, 5)
print(choice)

[5 4 6 6 2]


In [12]:
# 중복 허용하지 않을 때
choice = np.random.choice(d, 5, replace = False)
print(choice)

[4 7 8 9 5]


In [19]:
# 확률을 지정하고 싶을 때
choice = np.random.choice(d, 5, p=[0.1, 0, 0.3, 0.4, 0.2])
print(choice)

[2 1 2 0 2]


## permutation 순열
* 순열 - 서로 다른 n개의 원소에서 r개를 중복없이 순서에 상관있게 선택하는 혹은 나열하는 것
* 무작위로 뽑되 원본이 유지됨

In [21]:
# permutation 순열
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[5 2 7 1 4 9 0 6 8 3]
[0 1 2 3 4 5 6 7 8 9]


## 정규분포를 따르는 난수 생성

* 정규 분포 : 평균이 0, 분산이 1
```
np.random.normal('평균', '표준편차', '갯수')
```

In [22]:
a = np.random.normal(0, 1, 3)  # 평균이 0이고 표준편차가 1인 난수를 3개 뽑아줘
print(a)
# 배열로 출력됨

[-0.48564022 -0.89150445  2.13888732]
